production:
  entity: Ivoz\Provider\Domain\Model\OutgoingDdiRulesPattern\OutgoingDdiRulesPattern
  fields:
    outgoingDdiRule:
      title: _('Outgoing DDI Rule Pattern')
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\OutgoingDdiRule\OutgoingDdiRule
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            OutgoingDdiRule.name: asc
      default: true
    type:
      title: _('Type')
      type: select
      required: true
      source:
        data: inline
        values:
          'prefix':
            title: _("Prefix")
            visualFilter:
              show: [ prefix ]
              hide: [ matchList ]
          'destination':
            title: _("Destination")
            visualFilter:
              show: [ matchList ]
              hide: [ prefix ]
    prefix:
      title: _('Prefix')
      type: text
      trim: both
      pattern: "^[0-9]{1,3}[*]$"
      required: true
      default: true
      info:
        type: box
        position: left
        icon: help
        text: _("From 1 to 3 digits ended by * symbol")
        label: _("Need help?")
    matchList:
      title: _('Match List')
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\MatchList\MatchList
          filterClass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            MatchList.name: asc
        'null': _("Unassigned")
    action:
      title: _('Action')
      type: select
      required: true
      source:
        data: inline
        values:
          'keep':
            title: _("Keep Original DDI")
            visualFilter:
              show: []
              hide: ["forcedDdi"]
          'force':
            title: _("Force DDI")
            visualFilter:
              show: ["forcedDdi"]
              hide: []
    forcedDdi:
      title: _('Forced DDI')
      type: select
      source:
        data: mapper
        config:
          entity:  \Ivoz\Provider\Domain\Model\Ddi\Ddi
          filterClass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - ddie164
            template: '%ddie164%'
          order:
            Ddi.ddie164: asc
        'null': _("Client's default")
    forcedDDI:
      title: _('Forced DDI')
      type: ghost
      source:
        class: IvozProvider_Klear_Ghost_OutgoingRule
        method: getOutgoingRulePatternForcedDDI
    priority:
      title: _('Priority')
      type: number
      defaultValue: 1
      source:
        control: Spinner
    rule:
      title: _('Rule')
      type: ghost
      source:
        class: IvozProvider_Klear_Ghost_OutgoingRule
        method: getPatternRule
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
