#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/documentationLink.yaml


production:
  main:
    module: klearMatrix
    defaultScreen: ddiProviderRegistrationsList_screen
  screens:
    ddiProviderRegistrationsList_screen: &ddiProviderRegistrationsList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *DdiProviderRegistrations
      class: ui-silk-server-link
      title: _("List of %s %2s", ngettext('DDI Provider Registration', 'DDI Provider Registrations', 0), "[format| (%parent%)]")
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/brand/providers/ddi_providers.html#ddi-provider-registrations"
      fields:
        blacklist:
          contactUsername: true
          realm: true
          expires: true
          authUsername: true
          authPassword: true
          authProxy: true
          multiDDI: true
        order:
          username: true
          domain: true
        options:
          title: _("Options")
          screens:
            ddiProviderRegistrationsEdit_screen: true
          dialogs:
            ddiProviderRegistrationsDel_dialog: true
          default: ddiProviderRegistrationsEdit_screen
      options:
        title: _("Options")
        screens:
          ddiProviderRegistrationsNew_screen: true
        dialogs:
          ddiProviderRegistrationsDel_dialog: true
    ddiProviderRegistrationsNew_screen: &ddiProviderRegistrationsNew_screenLink
      <<: *DdiProviderRegistrations
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('DDI Provider Registration', 'DDI Provider Registrations', 1))
      shortcutOption: N
      fields: &ddiProviderRegistrationsFields_link
        blacklist:
          statusIcon: true
        order:
          username: true
          domain: true
          authPassword: true
          multiDDI: true
          contactUsername: true
          authUsername: true
          authProxy: true
          realm: true
          expires: true
      fixedPositions: &ddiProviderRegistrationsFixedPositions_link
        group0:
          label: _("Main Settings")
          colsPerRow: 12
          fields:
            username: 5
            domain: 5
            authPassword: 12
        group1:
          label: _("Contact Settings")
          colsPerRow: 12
          collapsed: true
          fields:
            multiDDI: 6
            contactUsername: 6
        group2:
          label: _("Optional Settings")
          colsPerRow: 12
          collapsed: true
          fields:
            authUsername: 5
            authProxy: 5
            realm: 6
            expires: 6
    ddiProviderRegistrationsEdit_screen: &ddiProviderRegistrationsEdit_screenLink
      <<: *DdiProviderRegistrations
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('DDI Provider Registration', 'DDI Provider Registrations', 1), "[format| (%item%)]")
      fields:
        <<: *ddiProviderRegistrationsFields_link
      fixedPositions:
        <<: *ddiProviderRegistrationsFixedPositions_link
  dialogs: &ddiProviderRegistrations_dialogsLink
    ddiProviderRegistrationsDel_dialog: &ddiProviderRegistrationsDel_dialogLink
      <<: *DdiProviderRegistrations
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('DDI Provider Registration', 'DDI Provider Registrations', 1))
      description: _("Do you want to delete this %s?", ngettext('DDI Provider Registration', 'DDI Provider Registrations', 1))
      message: _("%s successfully deleted.", ngettext('DDI Provider Registration', 'DDI Provider Registrations', 1))
      multiItem: 1
      labelOnList: 1
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
