Ivoz\Provider\Domain\Model\RatingPlanGroup\Description:
  type: embeddable
  fields:
    en:
      type: string
      nullable: false
      length: 255
      options:
        fixed: false
      column: description_en
    es:
      type: string
      nullable: false
      length: 255
      options:
        fixed: false
      column: description_es
    ca:
      type: string
      nullable: false
      length: 255
      options:
        fixed: false
      column: description_ca
    it:
      type: string
      nullable: false
      length: 255
      options:
        fixed: false
      column: description_it
