########################################
## Raw
########################################
Ivoz\Kam\Domain\Model\UsersLocation\RegistrationStatus:
  itemOperations: []
  collectionOperations: []

Ivoz\Kam\Domain\Model\UsersCdr\UsersCdr:
  properties:
    company:
      attributes:
        swagger_context:
          deprecated: true
          description: "Will be removed in the next release as it can be resolved automatically"
  attributes:
    pagination_client_enabled: true
    access_control: '("ROLE_COMPANY_ADMIN" in roles) or ("ROLE_COMPANY_USER" in roles)'
    read_access_control:
      ROLE_COMPANY_ADMIN:
        company:
          eq: "user.getCompany().getId()"
      ROLE_COMPANY_USER:
        company:
          eq: "user.getCompany().getId()"
  itemOperations:
    get: ~
  collectionOperations:
    get:
      swagger_context:
        produces:
        - 'application/json'
        - 'application/ld+json'
        - 'text/csv'
    get_my_call_history:
      method: 'GET'
      path: '/my/call_history'
      route_name: 'get_my_call_history'
      swagger_context:
        produces:
        - 'application/json'
        - 'application/ld+json'
        - 'text/csv'
        tags:
        - My
  attributes:
    pagination_client_enabled: true
